# Generated by Django 3.0 on 2021-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_auto_20211025_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='days_available',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='SAT', max_length=30),
        ),
    ]
