# Generated by Django 3.0 on 2021-10-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_auto_20211026_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='days_available',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='avail_fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='avail_mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='avail_thurs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='avail_tues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='avail_wed',
            field=models.BooleanField(default=False),
        ),
    ]
